# Generated by Django 5.1.4 on 2024-12-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Iterm',
        ),
        migrations.DeleteModel(
            name='Mason',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
