# Generated by Django 5.1.4 on 2024-12-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MSystem', '0002_delete_customer_delete_iterm_delete_mason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phone_number', models.IntegerField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7)),
                ('contact_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.TextField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSystem.customer')),
                ('mason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSystem.mason')),
            ],
        ),
        migrations.CreateModel(
            name='Iterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('iterm', models.FileField(upload_to='iterms/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSystem.order')),
            ],
        ),
    ]
