# Generated by Django 5.1.4 on 2024-12-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0005_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
