# Generated by Django 5.1.4 on 2024-12-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0007_customer_mobile_number_mason_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.IntegerField(default='000-000-0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='mason',
            name='mobile_number',
            field=models.IntegerField(default='000-000-0000', max_length=10),
        ),
    ]
