# Generated by Django 5.1.4 on 2024-12-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0010_alter_customer_mobile_number_alter_mason_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mason',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mason',
            name='mobile_number',
            field=models.CharField(default='000-000-0000', max_length=10, unique=True),
        ),
    ]
