# Generated by Django 5.1.4 on 2025-01-18 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0011_alter_mason_email_alter_mason_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='mason',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='mason',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mason',
            name='speciakity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('materials', 'Order for Materials'), ('mason', 'Request for Mason')], default='materials', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='mason',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mason',
            field=models.ForeignKey(blank=True, help_text='Select a mason if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MSystem.mason'),
        ),
    ]
