# Generated by Django 5.1.4 on 2025-01-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0013_rename_speciakity_mason_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
