# Generated by Django 5.1.4 on 2025-01-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0015_product_rename_amount_order_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
