# Generated by Django 5.1.4 on 2025-01-26 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0016_remove_order_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid for the order', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money')], default='cash', help_text='Method used for payment', max_length=20)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the payment was made')),
                ('reference_number', models.CharField(blank=True, help_text='Optional payment reference number', max_length=100, null=True)),
                ('order', models.ForeignKey(help_text='Related order for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='MSystem.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.DeleteModel(
            name='Iterm',
        ),
    ]
