# Generated by Django 5.1.4 on 2025-01-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0018_order_total_price_orderproduct_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
