# Generated by Django 5.1.4 on 2025-01-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0019_remove_orderproduct_price_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(blank=True, help_text='Select a mason if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MSystem.product'),
        ),
    ]
