# Generated by Django 5.1.4 on 2025-01-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0020_remove_order_products_delete_orderproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Total price of the order', max_digits=10),
        ),
    ]
