# Generated by Django 5.1.4 on 2025-01-26 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSystem', '0022_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ForeignKey(blank=True, help_text='Select a mason if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MSystem.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of the order', max_digits=10),
        ),
    ]
